### ISSUE TITLE
stdout piping

### ISSUE THREAD

**Issue by 12D687** [lkrg-org/lkrg#247]
I wonder If there is any possibility to pipe the lkrg output for custom logfile. Because it's cumbersome and unreliable for reading kernel buffer using dmesg.

**Comment by solardiz** [comment]
Instead of using the `dmesg` command, you can use one of the underlying kernel interfaces, which are:

1. `/dev/kmsg`. If you do a `SEEK_END` on it, you'll only be reading newly appearing messages. Such reads don't affect other readers from that pseudo-file.
2. `/proc/kmsg`. Reads _do_ affect other readers (whatever has been read disappears for all readers).
3. Various sub-calls of `syslog(2)`.

I recommend the first option.

Does this address your question/need?

**Comment by solardiz** [comment]
Also, how custom does your log file need to be? Most distros either readily direct kernel messages to a separate log file or use systemd journal, in which case `journalctl -k` (you can also add `-f`) will show you kernel messages only.

So you can do e.g.:

```
journalctl -kf --lines=0 | fgrep --line-buffered ' kernel: LKRG: ' > new-lkrg-messages
```

**Comment by solardiz** [comment]
Not an issue we need to track, so I'm closing, but please feel free to add further comments anyway.
