### ISSUE TITLE
insmod error

### ISSUE THREAD

**Issue by 12D687** [lkrg-org/lkrg#248]
When I try to load lkrg ( sudo insmod output/lkrg.ko kint_enforce=1
) I face this issue.
insmod: ERROR: could not insert module output/lkrg.ko: Operation not permitted

**Comment by solardiz** [comment]
My best guess is you do not really have root, not even after `sudo` - are you perhaps running this in a container?
Also, does anything appear in `dmesg`?

Not an issue we need to track, so closing it, but please feel free to add comments.

**Comment by 12D687** [comment]
I don't know if you see this
I try to run without root privileges and I face this issue again. Secondly I'm not running lkrg in container. Also you said in the readme in section Testing run insmod command whit sudo privileges. As well nothing appears in dmesg.

**Comment by solardiz** [comment]
Of course, this needs to be run as root. I never said nor implied otherwise.

If your `sudo` works correctly, this isn't in a container, and nothing appears in `dmesg`, then I don't have a good guess as to what the problem may be.

As you had also opened a different issue, it sounds like you were successfully running LKRG on some other system, correct? If so, you'll need to figure out what's different between the systems or/and between your actions.

**Comment by 12D687** [comment]
I apologize. When I run the command again and then look dmesg. Then it says: Lockdown: insmod: unsigned module loading is restricted; see man kernel_lockdown.7 
It's just kernel lockdown nothing serious.
It just my mistake. Nevermind it
